### cartpole 개요

In [1]:
# 트랙에 cart 1개
# 1개의 pole
# cart에 +1 또는 -1의 힘을 주어 조절
# 막대기가 서있으면 time step마다 +1의 보상
# 종료 조건
#  막대기가 12도 이상 기울어짐
#  카트가 중심으로부터 2.4 이상 벗어남
#  time step > 500
#  100 번 시도에서 평균 195.0 이상의 점수를 얻으면 해결

In [2]:
# 랜덤 액션

import warnings

warnings.filterwarnings("ignore")

from gymnasium.experimental.wrappers import RecordVideoV0
from IPython.display import Video
import gym

env = gym.make("CartPole-v1", render_mode='rgb_array')
env = RecordVideoV0(env, "video", name_prefix="cartpole1", disable_logger=True,episode_trigger=lambda x: x % 10 == 0 )
env.reset()

for _ in range(1000):
    env.render()
    env.step(env.action_space.sample())     # Take a random action
env.close()

c:\Python3.9.13\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [3]:
Video("video/cartpole1-episode-0.mp4", embed=True)

In [4]:
#관찰

env = gym.make('CartPole-v1')

observation = env.reset()

print(observation)

# [카트의 위치, 카트의 속도, 막대의 각도, 막대의 회전율]

(array([-0.00414631,  0.03717085, -0.03348782, -0.03592595], dtype=float32), {})


In [ ]:
env = gym.make('CartPole-v1')

observation = env.reset()
action = env.action_space.sample()

print(action) # 0,1 중 하나

In [5]:
env = gym.make('CartPole-v1')

observation = env.reset()
action = env.action_space.sample() #선택된 행동(0,1)

step = env.step(action)

print('First observation:', observation)
print('Action:', action)
print('Step:', step)

First observation: (array([-0.03296256, -0.01707192,  0.03828917, -0.02718617], dtype=float32), {})
Action: 0
Step: (array([-0.033304  , -0.21272145,  0.03774545,  0.2773273 ], dtype=float32), 1.0, False, False, {})


In [7]:
env = gym.make('CartPole-v1')

for i_episode in range(20):
  observation = env.reset()[0]
  for t in range(100):                        
      env.render()
      print(observation)
      action = env.action_space.sample()      
      observation, reward, done, info = env.step(action)[:4]
      if done:                                
          print('Episode finished after {} timesteps'.format(t+1))
          break

env.close()

[ 0.02132834 -0.00280752 -0.04048917  0.03573846]
[ 0.02127219 -0.19732615 -0.0397744   0.31537673]
[ 0.01732567 -0.00166088 -0.03346686  0.01042035]
[ 0.01729245 -0.19628729 -0.03325845  0.29235905]
[ 0.0133667  -0.39091966 -0.02741127  0.57436997]
[ 0.00554831 -0.5856468  -0.01592387  0.85829306]
[-0.00616463 -0.7805482   0.00124199  1.1459267 ]
[-0.02177559 -0.9756864   0.02416052  1.4389988 ]
[-0.04128932 -1.1710975   0.0529405   1.7391325 ]
[-0.06471127 -1.3667811   0.08772315  2.0478039 ]
[-0.09204689 -1.5626862   0.12867923  2.3662891 ]
[-0.12330061 -1.7586961   0.176005    2.6956005 ]
Episode finished after 12 timesteps
[0.03612563 0.03093949 0.03662679 0.03113661]
[ 0.03674442 -0.16468804  0.03724952  0.33514696]
[ 0.03345066 -0.3603198   0.04395246  0.63933986]
[ 0.02624427 -0.1658373   0.05673925  0.36081573]
[0.02292752 0.02843415 0.06395557 0.08654988]
[ 0.0234962  -0.16754347  0.06568657  0.39870542]
[0.02014533 0.02658812 0.07366067 0.127434  ]
[ 0.0206771  -0.16950753  

In [8]:
#공간

env = gym.make('CartPole-v1')
print(env.action_space)

# Discrete(2) 이산형(0,1)
print(env.observation_space)

# Box : n차원의 박스, 4개의 숫자

Discrete(2)
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)


In [9]:
print(env.observation_space.high) #카트의 위치( -4.8 ~ 4.8 )
print(env.observation_space.low) #막대의 각도 ( -0.419 ~ 0.419 )

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [10]:
# 행동 0 반복

env = gym.make('CartPole-v1', render_mode='rgb_array')
env = RecordVideoV0(env, "video", name_prefix="cartpole-left")

env.reset()

for i in range(50):
    env.render()
    observation, reward, done, info = env.step(0)[:4]
    print(observation, done)

env.close()

[-0.0467331  -0.15628229 -0.03099961  0.2629627 ] False
[-0.04985875 -0.35094836 -0.02574036  0.5457091 ] False
[-0.05687772 -0.54569936 -0.01482617  0.83017194] False
[-0.06779171 -0.74061555  0.00177726  1.1181554 ] False
[-0.08260401 -0.9357608   0.02414037  1.4113953 ] False
[-0.10131923 -1.1311736   0.05236828  1.7115257 ] False
[-0.1239427  -1.3268564   0.08659879  2.0200367 ] False
[-0.15047982 -1.5227625   0.12699953  2.338223  ] False
[-0.18093508 -1.7187806   0.17376398  2.6671197 ] False
[-0.2153107  -1.9147164   0.22710638  3.0074272 ] True
[-0.253605   -2.1102722   0.28725493  3.3594258 ] True
[-0.29581046 -2.3050275   0.35444343  3.722885  ] True
[-0.34191102 -2.49842     0.42890114  4.0969796 ] True
[-0.3918794 -2.6897347  0.5108407  4.480225 ] True
[-0.44567412 -2.8781042   0.6004452   4.8704467 ] True
[-0.5032362  -3.0625281   0.69785416  5.264807  ] True
[-0.56448674 -3.241915    0.8031503   5.6598997 ] True
[-0.62932503 -3.415152    0.9163483   6.051902  ] True
[-0.6

Moviepy - Done !
Moviepy - video ready c:\workspace3\230926\video\cartpole-left-episode-0.mp4


In [11]:
# 카트 속도 왼쪽 방향으로 증가,
# 막대의 각도 오른쪽으로 증가

Video("video/cartpole-left-episode-0.mp4", embed=True)

In [12]:
#행동 1 반복

env = gym.make('CartPole-v1', render_mode='rgb_array')
env = RecordVideoV0(env, "video", name_prefix="cartpole-right")

env.reset()

for i in range(50):
    env.render()

    observation, reward, done, info = env.step(1)[:4]
    print(observation, done)

env.close()

[ 0.01338399  0.19024472 -0.04065477 -0.27802873] False
[ 0.01718888  0.38592234 -0.04621535 -0.58325183] False
[ 0.02490733  0.5816603  -0.05788039 -0.8901277 ] False
[ 0.03654053  0.7775178  -0.07568294 -1.2004293 ] False
[ 0.05209089  0.9735327  -0.09969153 -1.5158396 ] False
[ 0.07156154  1.1697096  -0.13000832 -1.8379047 ] False
[ 0.09495573  1.3660065  -0.1667664  -2.16798   ] False
[ 0.12227587  1.562319   -0.21012601 -2.507166  ] True
[ 0.15352224  1.758463   -0.26026934 -2.856234  ] True
[ 0.18869151  1.9541548  -0.31739402 -3.2155437 ] True
[ 0.2277746  2.1489923 -0.3817049 -3.5849574] True
[ 0.27075446  2.3424373  -0.45340404 -3.9637578 ] True
[ 0.3176032  2.5338056 -0.5326792 -4.350587 ] True
[ 0.3682793   2.7222674  -0.61969095 -4.7434187 ] True
[ 0.42272466  2.906865   -0.7145593  -5.1395783 ] True
[ 0.48086196  3.0865529  -0.81735086 -5.5358315 ] True
[ 0.542593   3.260264  -0.9280675 -5.9285245] True
[ 0.6077983  3.4270015 -1.046638  -6.31377  ] True
[ 0.6763383  3.5859

Moviepy - Done !
Moviepy - video ready c:\workspace3\230926\video\cartpole-right-episode-0.mp4


In [13]:
# 카트 속도 오른쪽 방향으로 증가
# 막대의 각도 왼쪽으로 증가

Video("video/cartpole-right-episode-0.mp4", embed=True)

In [15]:
# 좌우 이동 : 막대가 오른쪽으로 기울어져 있으면 오른쪽으로 힘, 그렇지 않으면, 왼쪽으로 힘

env = gym.make('CartPole-v1', render_mode='rgb_array')

env = RecordVideoV0(env, "video", name_prefix="cartpole-method1")

observation = env.reset()[0]

for i in range(200):
    env.render()

    if observation[2] > 0:
        action = 1
    else: action = 0

    observation, reward, done, info = env.step(action)[:4]
    print(observation, done)

    # if done:
    #     print(i+1)
    #     break

env.close()

[-0.04243503 -0.21838674 -0.0071893   0.25840023] False
[-0.04680277 -0.41340533 -0.0020213   0.5488069 ] False
[-0.05507087 -0.6084988   0.00895484  0.84085226] False
[-0.06724085 -0.41350025  0.02577189  0.55099887] False
[-0.07551085 -0.21874957  0.03679186  0.26654595] False
[-0.07988585 -0.02417151  0.04212278 -0.01430927] False
[-0.08036928  0.17032182  0.0418366  -0.29341006] False
[-0.07696284  0.3648231   0.0359684  -0.5726103 ] False
[-0.06966638  0.55942273  0.02451619 -0.85374856] False
[-0.05847792  0.7542021   0.00744122 -1.1386228 ] False
[-0.04339388  0.94922596 -0.01533124 -1.4289627 ] False
[-0.02440936  0.75429666 -0.04391049 -1.1411103 ] False
[-0.00932343  0.5597753  -0.0667327  -0.8625151 ] False
[ 0.00187208  0.36562234 -0.083983   -0.5915387 ] False
[ 0.00918452  0.17177033 -0.09581377 -0.32644758] False
[ 0.01261993 -0.02186617 -0.10234272 -0.06545117] False
[ 0.01218261 -0.21538325 -0.10365175  0.19326931] False
[ 0.00787494 -0.40888152 -0.09978636  0.45153984

Moviepy - Done !
Moviepy - video ready c:\workspace3\230926\video\cartpole-method1-episode-0.mp4


In [16]:
Video("video/cartpole-method1-episode-0.mp4", embed=True)

In [17]:
# #신경망 학습

# import tensorflow as tf

# import numpy as np

# env = gym.make('CartPole-v1')

# # 4개의 입력, 2개의 출력
# model = tf.keras.models.Sequential([

#   tf.keras.layers.Dense(128, input_shape=(4,), activation=tf.nn.relu),

#   tf.keras.layers.Dense(2)

# ])

# observation = env.reset()[0]

# predict = model.predict(observation.reshape(1, 4))

# action = np.argmax(predict)

# print(observation)

# print(predict)

# print(action) # 더 큰 값인 0 선택

In [18]:
# #신경망 훈련

# env = gym.make('CartPole-v1')

# model = tf.keras.models.Sequential([

#   tf.keras.layers.Dense(128, input_shape=(4,), activation=tf.nn.relu),

#   tf.keras.layers.Dense(2)

# ])

# score = []

# for i in range(100):

#   print(i, end=' ')

#   observation = env.reset()[0]

#   for t in range(200):

#       predict = model.predict(observation.reshape(1, 4), verbose=None)

#       action = np.argmax(predict)

#       observation, reward, done, info = env.step(action)[:4]

#       if done:

#           score.append(t + 1)

#           break

# env.close()

# print(score)

In [19]:
# import matplotlib.pyplot as plt

# plt.plot(score)

# plt.xlabel('episode')

# plt.ylabel('score')

# plt.show()

# print(np.max(score))

# # 점수가 개선되지 않음

In [ ]:
# #Q learning

# import random

# import tensorflow as tf

# from collections import deque

# model = tf.keras.models.Sequential([

#     tf.keras.layers.Dense(24, input_dim=4, activation=tf.nn.relu),

#     tf.keras.layers.Dense(24, activation=tf.nn.relu),

#     tf.keras.layers.Dense(2, activation='linear')

# ])

# model.compile(optimizer='adam',

#               loss='mean_squared_error')

# model.summary()

In [ ]:
# import numpy as np

# score = []

# memory = deque(maxlen=2000)

# env = gym.make("CartPole-v1", render_mode='rgb_array')

# env = RecordVideoV0(env, "video", name_prefix="cartpole-dqn", disable_logger=True,episode_trigger=lambda x: x )

# for i in range(500):
#     state = env.reset()[0]

#     state = np.reshape(state, [1, 4])

#     eps = 1 / (i / 50 + 10)

#     for t in range(200):

#         # e-greedy

#         if np.random.rand() < eps:

#             action = np.random.randint(0, 2)

#         else:

#             predict = model.predict(state,verbose=None)

#             action = np.argmax(predict)

#         next_state, reward, done, _ = env.step(action)[:4]

#         next_state = np.reshape(next_state, [1, 4])

#         memory.append((state, action, reward, next_state, done))

#         state = next_state

#         if done or t == 199:

#             print('Episode', i, 'Score', t + 1)

#             score.append(t + 1)

#             break

#     # Training

#     if i > 10:

#         minibatch = random.sample(memory, 16)

#         for state, action, reward, next_state, done in minibatch:

#             target = reward

#             if not done:

#                 target = reward + 0.9 * np.amax(model.predict(next_state,verbose=None)[0])

#             target_outputs = model.predict(state,verbose=None)

#             target_outputs[0][action] = target

#             model.fit(state, target_outputs, epochs=1, verbose=None)

# env.close()

# print(score)

In [ ]:
# import matplotlib.pyplot as plt

# plt.plot(score)

# plt.xlabel('episode')

# plt.ylabel('score')

# plt.show()

# print(np.max(score))

In [ ]:
# Video("video/cartpole-dqn-episode-13.mp4", embed=True)

In [ ]:
# import numpy as np

# import tensorflow as tf

# from tensorflow import keras

# num_inputs = 4

# num_actions = 2

# num_hidden = 128

# experience_buffer=[]

# inputs = keras.layers.Input(shape=(num_inputs,))

# common = keras.layers.Dense(num_hidden, activation="relu")(inputs)

# action = keras.layers.Dense(num_actions, activation="softmax")(common)

# critic = keras.layers.Dense(1)(common)

# model = keras.Model(inputs=inputs, outputs=[action, critic])

In [ ]:
# eps = 0.0001
# def discounted_rewards(rewards,gamma=0.99,normalize=True):

#     ret = []

#     s = 0

#     for r in rewards[::-1]:

#         s = r + gamma * s

#         ret.insert(0, s)

#     if normalize:

#         ret = (ret-np.mean(ret))/(np.std(ret)+eps)

#     return ret

In [ ]:
# def run_episode(episode,max_steps_per_episode = 10000,render=False):    

#     states, actions, probs, rewards, critic = [],[],[],[],[]

#     state = env.reset()[0]

#     for _ in range(max_steps_per_episode):

#         if render:

#             env.render()

#         action_probs, est_rew = model(np.expand_dims(state,0))

#         action = np.random.choice(num_actions, p=np.squeeze(action_probs[0]))

#         nstate, reward, done, info = env.step(action)[:4]

#         if done:

#             break

#         states.append(state)

#         actions.append(action)

#         probs.append(tf.math.log(action_probs[0,action]))

#         rewards.append(reward)

#         critic.append(est_rew[0,0])

#         state = nstate

#         experience_buffer.append({

#                 'frame': env.render(),

#                 'episode': episode+1,

#                 'state': state,

#                 'action': action,

#                 'reward': sum(rewards)

#                 }

#             )
#     return states, actions, probs, rewards, critic

In [ ]:
# optimizer = keras.optimizers.Adam(learning_rate=0.01)

# huber_loss = keras.losses.Huber()

# episode_count = 0

# running_reward = 0

# experience_buffer=[]

# from gymnasium.experimental.wrappers import RecordVideoV0

# from IPython.display import Video

# env = gym.make("CartPole-v1", render_mode='rgb_array')

# env = RecordVideoV0(env, "video", name_prefix="cartpole", disable_logger=True,episode_trigger=lambda x: x % 10 == 0 )

# env.reset()

# while True:  

#     state,_ = env.reset()

#     episode_reward = 0

#     with tf.GradientTape() as tape:

#         if len(experience_buffer)>5000:

#             experience_buffer=experience_buffer[5000:]

#         _,_,action_probs, rewards, critic_values = run_episode(episode=episode_count)

#         episode_reward = np.sum(rewards)

        

#         running_reward = 0.05 * episode_reward + (1 - 0.05) * running_reward

#         dr = discounted_rewards(rewards)

#         actor_losses = []

#         critic_losses = []
#         for log_prob, value, rew in zip(action_probs, critic_values, dr):

#             diff = rew - value # reward - value

#             actor_losses.append(-log_prob * diff)

#             critic_losses.append(

#                 huber_loss(tf.expand_dims(value, 0), tf.expand_dims(rew, 0))

#             )

            

#         loss_value = sum(actor_losses) + sum(critic_losses)

#         grads = tape.gradient(loss_value, model.trainable_variables)

#         optimizer.apply_gradients(zip(grads, model.trainable_variables))

            

#     episode_count += 1

#     if episode_count % 10 == 0:

#         template = "running reward: {:.2f} at episode {}"

#         print(template.format(running_reward, episode_count))

#     if running_reward > 195:  

#         print("Solved at episode {} with {:.2f} running reward: !".format(episode_count,running_reward))

#         break

# env.close()    

In [ ]:
# Video("video/cartpole-episode-10.mp4", embed=True)

In [ ]:
# Video("video/cartpole-episode-180.mp4", embed=True)