# CNN
### 기본예제

In [1]:
#합성곱

import numpy as np

w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

#w 배열을 뒤집어서 출력
w_r = np.flip(w)
print(w_r)

#합성곱 계산
# w_r을 x의 왼쪽 자리에 맞추고 각 인덱스마다 곱한 후 더함
# 2x3 + 8x5 + 3x1 + 7x2 = 63
# w_r을 오른쪽으로 한자리 shift하여 곱셈
for i in range(6):
    print(np.dot(x[i:i+4], w_r))


[3 5 1 2]
63
48
49
28
21
20


In [2]:
#사이파이에서 제공하는 합성곱 함수
#w를 뒤집어서 곱하는 방식

from scipy.signal import convolve

# valid - 원본 배열에 패딩을 추가하지 않는 방식
# 원본 이미지가 4x4인 경우 결과물이 3x3으로 줄어드는 방식
convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

In [3]:
#합성곱 신경망에서는 w를 뒤집지 않고 그대로 곱하는 교차상관 방식을 사용함
#초기 가중치값은 랜덤으로 만들어지므로 뒤집어서 곱하는 것과 뒤집지 않고 곱하는 것이 큰 의미가 없음
#정확히 표현하면 교차상관이지만 합성곱 신경망이라는 이름을 관례적으로 사용하고 있음
#교차상관 - w를 뒤집지 않고 곱하는 방식

from scipy.signal import correlate

correlate(x, w, mode='valid')   # 교차상관

array([48, 57, 24, 25, 16, 39])

In [4]:
#full 패딩 - 제로패딩을 한 후 연산을 하게 되면 원본 배열의 모든 원소가 연산에 동일하게 참여하게 됨

correlate(x, w, mode='full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [5]:
#출력 배열의 길이가 원본 배열의 길이와 같아지도록 제로 패딩을 추가하는 방식

#합성곱 신경망에서 많이 사용하는 방식
correlate(x, w, mode='same')

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

In [6]:
#2차원 배열에 대한 합성곱 계산

from scipy.signal import correlate2d

x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

w = np.array([[2, 0],
              [0, 0]])

correlate2d(x, w, mode='valid')

array([[ 2,  4],
       [ 8, 10]])

In [7]:
#제로패딩을 하여 원본과 같은 사이즈로 출력되도록 함

x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

w = np.array([[2, 0],
              [0, 0]])              

correlate2d(x, w, mode='same')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
#텐서플로에서 지원하는 합성곱 함수

import tensorflow as tf

#4차원 배열을 사용해야 함
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

with tf.device('/CPU:0'):
    # 입력값: reshape(batch, height, width, channel)              
    x_4d = x.astype(np.float64).reshape(1, 3, 3, 1) #실수형으로 입력해야 함

    # 필터(가중치) reshape(height,width,channel,가중치의개수)
    w_4d = w.reshape(2, 2, 1, 1)

    #SAME 대문자로 작성해야 함
    c_out = tf.nn.conv2d(x_4d, w_4d, strides=1, padding='SAME')

    #  텐서를 넘파이 배열로 변환
    print(c_out.numpy().reshape(3, 3))

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [10]:
#맥스풀링

# 입력값: reshape(샘플수, height, width, channel)
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

x = x.reshape(1, 4, 4, 1)

# ksize 커널사이즈 2x2, strides 이동간격
with tf.device('/CPU:0'):
    p_out=tf.nn.max_pool2d(x,ksize=2,strides=2,padding='SAME')

    print(p_out.numpy().reshape(2,2))

[[ 6.  8.]
 [14. 16.]]
