# 6) 문서요약(BERT)

In [1]:
from transformers import BartTokenizer, TFBartForConditionalGeneration

# 모델 및 토크나이저 불러오기

model = TFBartForConditionalGeneration.from_pretrained('facebook/bart-base')

tokenizer = BartTokenizer.from_pretrained('facebook/bart-base')

All PyTorch model weights were used when initializing TFBartForConditionalGeneration.

All the weights of TFBartForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBartForConditionalGeneration for predictions without further training.
c:\Python3.9.13\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\tjoeun\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as a

In [2]:
import re

article = """
Google LLC is an American multinational technology company focusing on search engine technology,
online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial
intelligence,[9] and consumer electronics. It has been referred to as "the most powerful company
in the world"[10] and one of the world's most valuable brands due to its market dominance,
data collection, and technological advantages in the area of artificial intelligence.
[11][12][13] Its parent company Alphabet is considered one of the Big Five American information
technology companies, alongside Amazon, Apple, Meta, and Microsoft.
Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students
 at Stanford University in California. Together they own about 14% of its publicly listed
 shares and control 56% of the stockholder voting power through super-voting stock. The company
 went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as 
 a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's Internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.[14]
The company has since rapidly grown to offer a multitude of products and services beyond Google 
Search, many of which hold dominant market positions. These products address a wide range of use 
cases, including email (Gmail), navigation (Waze & Maps), cloud computing (Cloud), web browsing 
(Chrome), video sharing (YouTube), productivity (Workspace), operating systems (Android), 
cloud storage (Drive), language translation (Translate), photo storage (Photos), video calling 
(Meet), smart home (Nest), smartphones (Pixel), wearable technology (Pixel Watch & Fitbit), 
music streaming (YouTube Music), video on demand (YouTube TV), artificial intelligence 
(Google Assistant), machine learning APIs (TensorFlow), AI chips (TPU), and more. Discontinued 
Google products include gaming (Stadia), Glass,[citation needed] Google+, Reader, Play Music, 
Nexus, Hangouts, and Inbox by Gmail.[15][16]
Google's other ventures outside of Internet services and consumer electronics include quantum 
computing (Sycamore), self-driving cars (Waymo, formerly the Google Self-Driving Car Project), 
smart cities (Sidewalk Labs), and transformer models (Google Brain).[17]
Google and YouTube are the two most visited websites worldwide followed by Facebook and Twitter.
Google is also the largest search engine, mapping and navigation application, email provider, 
office suite, video sharing platform, photo and cloud storage provider, mobile operating system, 
web browser, ML framework, and AI virtual assistant provider in the world as measured by market 
share. On the list of most valuable brands, Google is ranked second by Forbes[18] and fourth by 
Interbrand.[19] It has received significant criticism involving issues such as privacy concerns, 
tax avoidance, censorship, search neutrality, antitrust and abuse of its monopoly position.
"""

print("before:")
print(article)

article = re.sub(r"[:.]\[[0-9]+\](.*?)\([0-9]+\)|.?[([][0-9]+[])]|\n|\r", r"", article)

#       re      regular expression : 정규 표현식
#       sub(패턴, 대체값, 문장)
#           [패턴]
#           + 반복

print("after:")
print(article)

before:

Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial intelligence,[9] and consumer electronics. It has been referred to as "the most powerful company in the world"[10] and one of the world's most valuable brands due to its market dominance, data collection, and technological advantages in the area of artificial intelligence.[11][12][13] Its parent company Alphabet is considered one of the Big Five American information technology companies, alongside Amazon, Apple, Meta, and Microsoft.
Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of the stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google w

In [3]:
inputs = tokenizer([article], max_length=1024, return_tensors='tf', truncation=True)
inputs

{'input_ids': <tf.Tensor: shape=(1, 609), dtype=int32, numpy=
array([[    0, 20441,  2291,    16,    41,   470, 17043,   806,   138,
         5650,    15,  1707,  3819,   806,     6,   804,  4579,     6,
         3613, 11730,     6,  3034,  2257,     6, 17997, 11730,     6,
          364,    12,  8342,     6,  7350,  2316,     8,  2267,  8917,
            4,    85,    34,    57,  4997,     7,    25,    22,   627,
          144,  2247,   138,    11,     5,   232,     8,    65,     9,
            5,   232,    18,   144,  5130,  3595,   528,     7,    63,
          210, 12532,     6,   414,  2783,     6,     8,  9874, 12340,
           11,     5,   443,     9,  7350,  2316,  3139,  4095,   138,
        15023,    16,  1687,    65,     9,     5,  1776,  4934,   470,
          335,   806,   451,     6,  2863,  1645,     6,  1257,     6,
        37622,     6,     8,  3709,     4, 20441,    21,  4790,    15,
          772,   204,     6,  6708,     6,    30,  6045,  7086,     8,
        23509, 

In [4]:
inputs['input_ids'].numpy()

array([[    0, 20441,  2291,    16,    41,   470, 17043,   806,   138,
         5650,    15,  1707,  3819,   806,     6,   804,  4579,     6,
         3613, 11730,     6,  3034,  2257,     6, 17997, 11730,     6,
          364,    12,  8342,     6,  7350,  2316,     8,  2267,  8917,
            4,    85,    34,    57,  4997,     7,    25,    22,   627,
          144,  2247,   138,    11,     5,   232,     8,    65,     9,
            5,   232,    18,   144,  5130,  3595,   528,     7,    63,
          210, 12532,     6,   414,  2783,     6,     8,  9874, 12340,
           11,     5,   443,     9,  7350,  2316,  3139,  4095,   138,
        15023,    16,  1687,    65,     9,     5,  1776,  4934,   470,
          335,   806,   451,     6,  2863,  1645,     6,  1257,     6,
        37622,     6,     8,  3709,     4, 20441,    21,  4790,    15,
          772,   204,     6,  6708,     6,    30,  6045,  7086,     8,
        23509,  2265,   179,   150,    51,    58, 15221,   521,    23,
      

In [5]:
# 문장 요약 생성 결과(vocabulary ID)를 summary_ids에 저장
# num_beams : 의미있는 문장 후보군의 수

summary_ids = model.generate(inputs['input_ids'], num_beams=5, max_length=25)
summary_ids

<tf.Tensor: shape=(1, 25), dtype=int32, numpy=
array([[    2,     0, 20441,  2291,    16,    41,   470, 17043,   806,
          138,  5650,    15,  1707,  3819,   806,     6,   804,  4579,
            6,  3613, 11730,     6,  3034,  2257,     2]])>

In [6]:
print(''.join([tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in summary_ids]))

Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software
