### KMeans-색상선택 2

In [3]:
import numpy as np
import cv2

K = 16 # cluster 개수(16컬러)

img = cv2.imread('c:/workspace3/data/images/apple.jpg')
data = img.reshape((-1,3)).astype(np.float32)

# 최대 10회 반복, 1픽셀 이하이면 종료
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)

# 클러스터링(K 클러스터 개수, criteria 종료 기준)
ret,label,center=cv2.kmeans(data,K,None,criteria,10,cv2.KMEANS_RANDOM_CENTERS)

center = np.uint8(center)
print('중심좌표:',center)

res = center[label.flatten()]
res = res.reshape((img.shape))

merged = np.hstack((img, res))

cv2.imshow('KMeans Color',merged)
cv2.waitKey(0)

cv2.destroyAllWindows()

중심좌표: [[ 52 142 121]
 [180 206 213]
 [ 97 138 132]
 [ 16  31  28]
 [113 178 175]
 [ 47 177 158]
 [ 59 203 192]
 [ 56 107  94]
 [ 44  51 130]
 [ 32  76  59]
 [ 21  60  90]
 [ 72  53 163]
 [ 24  18 117]
 [110  91 186]
 [231 231 232]
 [164 173 191]]
